### ISSUE TITLE
Problems on 4.11

### ISSUE THREAD

**Issue by mrvanes** [bas-t/dvbloopback#13]
I'm trying to upgrade my kernel to 4.11 and seem to run into some dvbloopback problems.
I'm quite convinced that my dvb adapters still work:
```
# scan -a0 ziggo.conf
scanning ziggo.conf
using '/dev/dvb/adapter0/frontend0' and '/dev/dvb/adapter0/demux0'
initial transponder 474000000 6875000 0 3
>>> tune to: 474000000:INVERSION_AUTO:6875000:FEC_NONE:QAM_64
0x0000 0x4d25: pmt_pid 0x1130 Ziggo -- BBC First (running, scrambled)
0x0000 0x4d2b: pmt_pid 0x0ed8 Ziggo -- Secret Circle info (running, scrambled)
...

# scan -a1 ziggo.conf
scanning ziggo.conf
using '/dev/dvb/adapter1/frontend0' and '/dev/dvb/adapter1/demux0'
initial transponder 474000000 6875000 0 3
>>> tune to: 474000000:INVERSION_AUTO:6875000:FEC_NONE:QAM_64
Network Name 'Ziggo Network'
0x0000 0x4d25: pmt_pid 0x1130 Ziggo -- BBC First (running, scrambled)
0x0000 0x4d2b: pmt_pid 0x0ed8 Ziggo -- Secret Circle info (running, scrambled)
...
```

But when I use the first dvbloopback device I get the following error:
```
# scan -a2 ziggo.conf
scanning ziggo.conf
using '/dev/dvb/adapter2/frontend0' and '/dev/dvb/adapter2/demux0'
main:2745: FATAL: failed to open '/dev/dvb/adapter2/frontend0': 14 Bad address
```
But the dvbloopback device is there (at least the /dev tree):
```
# ls -1 /dev/dvb/adapter2/
audio0
audio1
demux0
demux1
dvr0
dvr1
frontend0
frontend1
osd0
osd1
video0
video1
```
The same is true for second loopback device, in case you wondered.

I've tried to apply the normal routine (patch dvbdev.c etc.) for baking dvbloopback in tree for 4.11, but may have missed a (new) step. Could you please shed some light on this?

**Comment by bas-t** [comment]
The dvbloopback device should be /dev/dvb/adapter2/frontend1, not frontend0

**Comment by mrvanes** [comment]
That's funny, because since as long as I remember, my MythTV configuration has always pointed to frontend0 (but I'm happy to change that if it helps). I doubt however if it will in this case:
```
# scan -a2 -f1 ziggo.conf
scanning ziggo.conf
using '/dev/dvb/adapter2/frontend1' and '/dev/dvb/adapter2/demux0'
Frontend can not do INVERSION_AUTO, trying INVERSION_OFF instead
initial transponder 474000000 6875000 0 3
>>> tune to: 474000000:INVERSION_OFF:6875000:FEC_NONE:QAM_64
WARNING: >>> tuning failed!!!
>>> tune to: 474000000:INVERSION_OFF:6875000:FEC_NONE:QAM_64 (tuning failed)
WARNING: >>> tuning failed!!!
ERROR: initial tuning failed
dumping lists (0 services)
Done
```
dmesg is flooded with these messages I notice now.
```
dvbloopback: Got wrong response (2147774277 != 18446744073709551615)
```
Also, using demux1 doesn't help. Any other ideas?

**Comment by bas-t** [comment]
Your comment about mythtv not beeing pointed directly to the dvbloopback device is correct.
The ffdecsawrapper binary takes care of communication between the two interfaces.
So if you are having the same trouble using mythtv, I suggest recompiling that ffdecsawrapper binary, using my descrambler repo.
Other then that, I'm pretty much clueless.
On my backend, no trouble with linux-4.11.

**Comment by mrvanes** [comment]
I try to understand the layers and I get that ffdecsawrapper is responsible for CA functionality when watching TV. I just want to test as short as possible chain that proves (or disproves) problems in each layer. That's why I started out using scan on the hardware device, which seems to work (agree?). Then, I assume, reaching out for the hardware via dvbloopback _without_ CA calls (scan?) should result in a 1-on-1 relay of IOCTL from dvbloopback to hardware? If that fails, am I wrong to conclude that it can only be a problem in dvbloopback and not ffdecswrapper? What is the difference between frontend0 and frontend1 in this regard?

I did some searching and the only place 'Got wrong response' appears is in dvb_loopback.c, in response to an attempt at getting an interruptable lock on lbdev object.

Hmm... I seem to get it, frontend1 is used by ffdecsawrapper to forward the calls made on 0, so forwarding will never succeed without ffdecsawrapper unless ffdecsawrapper isn't running and I address frontend1 directly as you suggested. If this fails, I think I have proven that dvbloopback IOCTL forwarding to hardware is broken, didn't I? So that takes ffdecsawrapper out of the loop?

When (recompiled as you suggested) ffdecawrapper is running, a scan on frontend0 fails and ffdecsawrapper crashes:
```
May 17 09:08:38 pandora systemd[1]: ffdecsawrapper.service: Main process exited, code=exited, status=255/n/a
May 17 09:08:38 pandora kill[5922]: Usage:
May 17 09:08:38 pandora kill[5922]:  kill [options] <pid> [...]
May 17 09:08:38 pandora kill[5922]: Options:
May 17 09:08:38 pandora kill[5922]:  <pid> [...]            send signal to every <pid> listed
May 17 09:08:38 pandora kill[5922]:  -<signal>, -s, --signal <signal>
May 17 09:08:38 pandora kill[5922]:                         specify the <signal> to be sent
May 17 09:08:38 pandora kill[5922]:  -l, --list=[<signal>]  list all signal names, or convert one to a name
May 17 09:08:38 pandora kill[5922]:  -L, --table            list all signal names in a nice table
May 17 09:08:38 pandora kill[5922]:  -h, --help     display this help and exit
May 17 09:08:38 pandora kill[5922]:  -V, --version  output version information and exit
May 17 09:08:38 pandora kill[5922]: For more details see kill(1).
May 17 09:08:38 pandora systemd[1]: ffdecsawrapper.service: Control process exited, code=exited status=1
May 17 09:08:38 pandora systemd[1]: ffdecsawrapper.service: Unit entered failed state.
May 17 09:08:38 pandora systemd[1]: ffdecsawrapper.service: Failed with result 'exit-code'.
May 17 09:08:39 pandora kernel: [ 1408.287350] dvblb_fake_ioctl interrupted: 1074818898
```
ffdecsawrapper.log starts normally and ends with at the moment I encounter a failed scan on frontend0
```
...
May 17 09:09:06.126 : Listening on port 5456
May 17 09:13:03.189 frontend: Didn't read enough data
```

**Comment by bas-t** [comment]
Can't comment on (the status of the version you use) scan, I never use it.
Again, no problems here using Mythtv and linux-4.11.1

**Comment by mrvanes** [comment]
scan is just a simple way to test dvb hardware. It tunes, locks and spits out channel information it finds in the program stream(s) on given frequency. If scan works, your hardware/signal work ;)
https://www.linuxtv.org/wiki/index.php/Scan

**Comment by mrvanes** [comment]
Ok, if you don't feel like helping me debug this problem please tell me. Until then I'll report my findings here to see if we can solve this together, ok?
Last thing I've noticed is that the 18446744073709551615 in syslog "Got wrong response" message is actually the ULONG_MAX set in ```dvblb_open``` @409 for the userspace case.

This means that  ```lbdev->ioctlcmd``` does not get set to any correct(?) command after ```dvblb_open``` and before ```dvblb_ioctl``` userspace case is called as expected by the ```if (cmd != lbdev->ioctlcmd)``` test?

I can find one line that assigns cmd to ```lbdev->ioctlcmd``` @268 but dvblb_fake_ioctl never gets called when frontend1 is addressed?

I see dvblb_open does a dvblb_fake_ioctl, but only if it's not ```lbdev->forward_dev```?

update: Testing in 4.10 shows that dvbloopback can't live without ffdecsawrapper, access to frontend1 shows the same problems. Back to the drawing board ;)

**Comment by mrvanes** [comment]
My apologies. I can't even get a lock on adapter0/frontend0 in MythTV anymore, so my dvb driver seems broken in 4.11, at least the way MythTV accesses it.

**Comment by bas-t** [comment]
Or scan for that matter...

**Comment by mrvanes** [comment]
Ha! Fixed it! It wasn't dvbloopback or ffdecsawrapper but mythbackend going bonkers after upgrade. It turns out dvb device enumeration is different in 4.11+ so mythbackend tried to connect to the first available dvb device for tuner1, which was adapter0, which was locked by dvbloopback of course. After tedious testing with and without dvbloopback I saw the error and have now reconfigured mythbackend to look at adapters2 and 3 and guess what... I'm on 4.14 and everything works like a charm.
Best news is that ddbridge module is now part of 4.14 so I don't need to compile ddbridge out of kernel anymore, and even better: the baytrail freeze issue seems to be resolved (but that still has to be tested).
Now it's waiting for dvbloopback to be accepted upstream. LOL! :)

On a sidenote: dvbloopback won't work with an exported dvb_usercopy anymore, it realy needs dvb_loopback's dvblb_usercopy. No big problem, but it may be a sign dvb-core changed a bit since you last copied dvb_usercopy?

**Comment by mrvanes** [comment]
For the sake of documentation I'd like to add that after ddbridge upgrade the delivery system of second tuner was erroneously set to DVBT2 and confuses MythTV while tuning. I use dvb-fe-tool to set it back to DVBC/ANNEX_A each time before mythbackend service starts.

**Comment by fendrychl** [comment]
@mrvanes can you please write more about how you figured out this problem? Maybe I have the same problem. I have mythtv with dvbloopback and time to time the stream stop working and dmesg is full of "dvblb_fake_ioctl interrupted:" messages.

Thank you. :)
