### ISSUE TITLE
Not detecting channel changes?

### ISSUE THREAD

**Issue by lokixxx** [bas-t/dvbloopback#14]
I'm running Ubuntu 18.04. I'm tuned to a channel but I don't see any activity in the ffdecsawrapper.log file.

Mar 26 06:31:44.735 : Listening on port 5456
Mar 26 06:33:43.737 CAM(core.net): idle timeout, disconnected 1.xxx.com:12345

Any idea what went wrong?

**Comment by bas-t** [comment]
I don't use this software anymore for quite some time. Can't help you. Maybe someone else can, so I'll leave this ticket open.
Cheers and good luck!
