### ISSUE TITLE
gawk installation missing in configure script

### ISSUE THREAD

**Issue by eiten** [bas-t/dvbloopback#15]
Hi there,

in your configuration script, gawk is not installed on ubuntu 18.04 LTS

Regards, Edi

**Comment by bas-t** [comment]
Why? What change is needed to address this issue?

**Comment by eiten** [comment]
Why this happens now, I don't know. With older Ubuntu-Releases, I did not have that issue. Now I used a vanilla 18.04 on VBox, and there this issue occured. Maybe with the older versions, I installed gawk at some point before compiling the loopback device kernel.

After a long time compiling, the build process failed with "gawk not found".

I would reccomend to add it somewhere after line 479, where you install the build dependencies.
# Get build-deps, Debian, Devuan and Ubuntu only.

Should I fork the repo, make the change and file a pull request?

Regards, Edi

**Comment by bas-t** [comment]
I pushed the change just now. It should fix your issue.

**Comment by eiten** [comment]
Perfekt, thanks. Will test it out again on a vanilla 18.04 and report back
