### ISSUE TITLE
Build failure on kernels >= 5.6.0

### ISSUE THREAD

**Issue by Strunzdesign** [bas-t/dvbloopback#16]
Hi,

with version 5.6.0 the Linux kernel changed its API. The interface of "proc_create_data()" changed to using "struct proc_ops" instead of "struct file_operations".

I created a small patch file "5.6-linux.patch" that can be applied easily. However, I would prefer to add these changes directly to your source code encapsulated in "#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 6, 0)" / "#else" / "#endif" statements. Currently, it seems that your repo is accumulating patch files. At least here on Gentoo Linux, it becomes quite challenging to apply this ever growing set of patch files and "sed" commands.

Please add this patch file to your repo, or better, apply it directly using those Kernel version guards. If you want me to help you with this, just tell me, then I'm going to prepare a pull request.

Regards,
Florian

**Comment by Strunzdesign** [comment]
*junk deleted*

**Comment by Strunzdesign** [comment]
I'm having problems with the upload feature. The patch file "5.6-linux.patch" is short:
```
--- drivers/media/pci/dvbloopback/dvblb_proc.c	2015-10-10 15:54:58.061168093 +0200
+++ drivers/media/pci/dvbloopback/dvblb_proc.c	2020-04-04 20:02:21.653061296 +0200
@@ -173,12 +173,11 @@
     return single_open(filep, dvblb_procfs_read, PDE_DATA(inode));
 }
 
-static const struct file_operations dvblb_procfs_fops = {
-    .owner      = THIS_MODULE,
-    .open       = dvblb_procfs_open,
-    .read       = seq_read,
-    .write      = dvblb_procfs_write,
-    .release    = single_release,
+static const struct proc_ops dvblb_procfs_fops = {
+    .proc_open       = dvblb_procfs_open,
+    .proc_read       = seq_read,
+    .proc_write      = dvblb_procfs_write,
+    .proc_release    = single_release,
 };
 
 int dvblb_init_procfs_device(struct dvblb *dvblb, struct dvblb_devinfo *lbdev)
@@ -197,12 +196,11 @@
     return single_open(filep, dvblb_procfs_adapter_read, PDE_DATA(inode));
 }
 
-static const struct file_operations dvblb_procfs_adapter_fops = {
-    .owner      = THIS_MODULE,
-    .open       = dvblb_procfs_adapter_open,
-    .read       = seq_read,
-    .write      = dvblb_procfs_adapter_write,
-    .release    = single_release,
+static const struct proc_ops dvblb_procfs_adapter_fops = {
+    .proc_open       = dvblb_procfs_adapter_open,
+    .proc_read       = seq_read,
+    .proc_write      = dvblb_procfs_adapter_write,
+    .proc_release    = single_release,
 };
 
 int dvblb_init_procfs_adapter(struct dvblb *dvblb)

```

**Comment by bas-t** [comment]
As you probably know, I'm not maintaining this repo anymore.
That being said, I'm willing to accept a proper pull request.
You'l have to explain to me what actually caused the problem you're experiencing and why your patch made it dissapeare.
Kind regards, Tycho

**Comment by bas-t** [comment]
Ah, I see your point. Nevertheless I would like you to make a pull request out of your patch, including the kernelversion #if #else #endif statements.
Tycho.

**Comment by bas-t** [comment]
Update:
that wońt work, since it is a in-tree kernel module. So kernelversion statements are forbidden. The only option is yet another patch that will be applied to the module prior to building it. So sorry.
Do you want me to include your patch like I always did (so the way you don't like)?
Regards, Tycho.

**Comment by Strunzdesign** [comment]
Hi,

I didn't know that kernel version statements are not available for in-kernel code. Thus, I see no other way than either adding this as a dedicated patch file, or, trying to mainline the code of the repo *scnr*

So, please add the file, and I'm not going to create a pull request... I planned to do that today, but you know, sometimes problems seem to resolve themselves ;-)

Regards,
Florian

**Comment by bas-t** [comment]
Please test, should anything be adjusted, please let me know.

**Comment by bas-t** [comment]
Hi Florian,
I screwed up some times on this, one tends to forget parts of the logic implemented when not dealing with it active anymore.
However, it's all fixed now.

**Comment by Strunzdesign** [comment]
I confirm it works on kernel 5.6.7. Thank you very much, and sorry for the delayed report!

Thanks again,
Florian
