### ISSUE TITLE
Anyone experiencing proc_dir_entry 'x' already registered?

### ISSUE THREAD

**Issue by bjorneg** [bas-t/dvbloopback#21]
I'm on Debian testing (5.7.10-1).
When modprobing dvbloopback I get:

[   45.192166] proc_dir_entry 'adapter1/sec' already registered

[   45.192176] WARNING: CPU: 0 PID: 2192 at fs/proc/generic.c:362 proc_register+0x128/0x170
[   45.192176] Modules linked in: dvbloopback(E+) ip6t_REJECT(E) nf_reject_ipv6(E) nf_log_ipv6(E) tda10021(E) xt_state(E) xt_multiport(E) ipt_REJECT(E) nf_reject_ipv4(E) xt_recent(E) xt_tcpudp(E) xt_conntrack(E) nf_conntrack(E) nf_defrag_ipv6(E) nf_defrag_ipv4(E) nf_log_ipv4(E) nf_log_common(E) nft_limit(E) xt_LOG(E) intel_rapl_msr(E) intel_rapl_common(E) xt_limit(E) nft_counter(E) ghash_clmulni_intel(E) xt_hashlimit(E) nft_compat(E) xfs(E) budget_av(E) saa7146_vv(E) videobuf_dma_sg(E) videobuf_core(E) budget_core(E) ttpci_eeprom(E) saa7146(E) dvb_core(E) videodev(E) mc(E) evdev(E) aesni_intel(E) libaes(E) crypto_simd(E) cryptd(E) glue_helper(E) rapl(E) pcspkr(E) xen_pcifront(E) nf_tables(E) nfnetlink(E) drm(E) ip_tables(E) x_tables(E) autofs4(E) btrfs(E) blake2b_generic(E) zstd_decompress(E) zstd_compress(E) raid10(E) raid456(E) async_raid6_recov(E) async_memcpy(E) async_pq(E) async_xor(E) async_tx(E) xor(E) raid6_pq(E) libcrc32c(E) crc32c_generic(E) raid1(E) raid0(E) multipath(E) linear(E)
[   45.192186]  md_mod(E) dm_mod(E) crct10dif_pclmul(E) crct10dif_common(E) xen_netfront(E) xen_blkfront(E) crc32_pclmul(E) crc32c_intel(E)
[   45.192189] CPU: 0 PID: 2192 Comm: modprobe Tainted: G            E     5.7.0-900-amd64 #1 Debian 5.7.10-1
[   45.192190] RIP: e030:proc_register+0x128/0x170
[   45.192191] Code: 25 18 36 01 00 5b 48 89 e8 5d 41 5c 41 5d c3 48 8b 95 a0 00 00 00 49 8b b4 24 a0 00 00 00 48 c7 c7 d8 51 f0 81 e8 6a e4 d3 ff <0f> 0b c6 05 f7 17 36 01 00 8b 45 5c 48 c7 c7 e0 9e 0a 82 8d b0 00
[   45.192191] RSP: e02b:ffffc900408d7c10 EFLAGS: 00010282
[   45.192192] RAX: 0000000000000000 RBX: ffff888036b7ebd8 RCX: 0000000000000007
[   45.192193] RDX: 0000000000000007 RSI: 0000000000000001 RDI: ffff88803e819ac0
[   45.192193] RBP: ffff88803c506c00 R08: 00000000000001a7 R09: 0000000000000004
[   45.192193] R10: 0000000000000000 R11: 0000000000000001 R12: ffff888036b7ed80
[   45.192194] R13: ffff888036b7ee00 R14: 0000000000000004 R15: ffff88803b2158d8
[   45.192199] FS:  00007f1f587b4540(0000) GS:ffff88803e800000(0000) knlGS:0000000000000000
[   45.192200] CS:  e030 DS: 0000 ES: 0000 CR0: 0000000080050033
[   45.192200] CR2: 000055da16c759b0 CR3: 0000000004788000 CR4: 0000000000040660
[   45.192202] Call Trace:
[   45.192205]  proc_create_data+0x39/0x50
[   45.192208]  dvblb_init_procfs_device+0x34/0x50 [dvbloopback]
[   45.192210]  create_lb_dev+0x172/0x238 [dvbloopback]
[   45.192211]  dvblb_init+0x1cf/0x1000 [dvbloopback]
[   45.192212]  ? 0xffffffffc08dd000
[   45.192214]  do_one_initcall+0x46/0x200
[   45.192216]  ? free_unref_page_commit+0x8b/0x110
[   45.192218]  ? _cond_resched+0x15/0x30
[   45.192220]  ? kmem_cache_alloc_trace+0x161/0x220
[   45.192221]  ? do_init_module+0x23/0x230
[   45.192222]  do_init_module+0x5c/0x230
[   45.192223]  load_module+0x234c/0x24f0
[   45.192225]  ? __do_sys_finit_module+0xaa/0x110
[   45.192226]  __do_sys_finit_module+0xaa/0x110
[   45.192227]  do_syscall_64+0x52/0x180
[   45.192229]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   45.192230] RIP: 0033:0x7f1f588d5a79
[   45.192231] Code: 00 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d e7 53 0c 00 f7 d8 64 89 01 48
[   45.192231] RSP: 002b:00007ffedc8c3ca8 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[   45.192232] RAX: ffffffffffffffda RBX: 0000563fc50ebcc0 RCX: 00007f1f588d5a79
[   45.192232] RDX: 0000000000000000 RSI: 0000563fc3f09358 RDI: 0000000000000003
[   45.192232] RBP: 0000000000040000 R08: 0000000000000000 R09: 0000000000000000
[   45.192233] R10: 0000000000000003 R11: 0000000000000246 R12: 0000563fc3f09358
[   45.192233] R13: 0000000000000000 R14: 0000563fc50ebdd0 R15: 0000563fc50ebcc0
[   45.192234] ---[ end trace 612e76cf849a80eb ]---
[   45.192263] ------------[ cut here ]------------

and then the same for:
- proc_dir_entry 'adapter1/frontend' already registered

Did I miss anything?

Works perfect here on Debian 4.19.67

**Comment by bas-t** [comment]
@bjorneg 
Maybe you should post your kernel config and the OS you are using as well. Could be the culprit.
However, please post such large items on a external site and link to your external post on this one.
Thanks, Tycho

**Comment by Strunzdesign** [comment]
This is a very similar crash dump as discussed in https://github.com/bas-t/dvbloopback/issues/18. I need to check the health of the master branch here again... time for another kernel update.

**Comment by bjorneg** [comment]
I'm on a plain vanilla Debian testing (5.7.10-1) amd64.
No changes to default Debian kernel config at all.

This is most likely a duplicate of what is mentioned in the end of issue #18 .

**Comment by Strunzdesign** [comment]
It should work now, I just tested it. Please test again, and report if you still encounter this issue.

**Comment by bjorneg** [comment]
Works for me now (Debian 5.8.0). Thanks!
