### ISSUE TITLE
Use Official TBS Drivers

### ISSUE THREAD

**Issue by dodoadoodoo** [bas-t/dvbloopback#3]
Any chance you can add building with the official TBS drivers to the configure script?

Big thanks for all your efforts with this!

**Comment by bas-t** [comment]
The dvbloopback module in this repo can only be compiled against a >=3.10.x kernel/media stack.
Afaik, the official TBS drivers media stack does not qualify.
Apart from that, I'm not willing to maintain the script for out of tree drivers I'll never use (and thus not being able to test)

**Comment by bas-t** [comment]
Hi, as it turns out, I already have what you want:
https://github.com/bas-t/dvbloopback-tbs
Just found it in my code base and, for your convenience, put it back online again.

I did proof-read the script and made some slight mods. You can test it if you want.
Again, I'm not going to actively maintain it, since I don't use closed source drivers.
If you point me to an obvious flaw, I'll correct that of course.

**Comment by dodoadoodoo** [comment]
Awesome, I'll try to find some time to test it during the weekend. (I only have one system, so need to test in production...)
Thank you for all your time and effort spent on this!
/D

**Comment by bas-t** [comment]
If you do, please make sure that you are starting out with a clean kernel+headers >=3.10.x
Furthermore, if you previously used opensource drivers + firmware, you'll have to completely poweroff your system for a couple of minutes (5 mins will do) before booting with the closed source TBS drivers.
I mean it: unplug your power cord.

I added debug tests and did a dry-run. I'm sure you'll have correctly configured, compiled and installed drivers using my repo.
Just run ./configure (or if you are using multistandard dvb adapters and need them in dvb-c mode: ./configure --dvbc=yes)

Cheers and have fun!

**Comment by dodoadoodoo** [comment]
Thanks for the tips. I'm on Ubuntu 14.04 so 3.13. Currently running your dvbloopback with Luis' drivers on a TBS 6984. It works well for a couple of weeks, but ultimately craps out requiring rmmod/modprobe circle. Never had any problems before, ran about 18 months on old dvbloopback + TBS drivers, so hoping this will help.
Thank you again
/D

**Comment by dodoadoodoo** [comment]
I have been on a longer trip but now I can finally report back. Process was incredibly smooth. These are the steps I took on an Ubuntu 14.04 initially running with dvbloopback and open source drivers.
1. Update to the latest kernel: apt-get dist-upgrade
2. Remove all references to kernel 900 (previously built by dvbloopback) in boot: cd /boot; rm _900_
3. Update grub: update-grub
4. Reboot into latest kernel version5. Clone https://github.com/bas-t/dvbloopback-tbs
5. ./configure with your favorite options. Wait
6. Reboot - mythtv working - woohoo
   /D

**Comment by dodoadoodoo** [comment]
Oh, and big thanks :-)
/D
