### ISSUE TITLE
configure problem

### ISSUE THREAD

**Issue by peje66** [bas-t/dvbloopback#4]
I saw this error scroll by:
./configure: line 1159: [: /lib/modules/4.2: binary operator expected

The issue is that `DEBIANKERNEL=$(echo `pwd` | grep -o '[[:digit:]]\+\.[[:digit:]]\+')`
does not work when there are more digits in the path.
for example: `echo  ~/src/dvbloopback-4.2/linux-4.2.5|grep -o '[[:digit:]]\+\.[[:digit:]]\+'` gives

```
4.2
4.2
```

Maybe add a `| tail -1`

Appreciate your work with ffdecsawrapper

/Peje

**Comment by bas-t** [comment]
That's because you rename the dvbloopback dir using digits. It is not supposed to contain any digits.
So, when you need to distinguish between several dvbloopback dirs, please use dvbloopback-four-dot-two or something like that.
