### ISSUE TITLE
ffdecsawrapper+dvblast

### ISSUE THREAD

**Issue by marian3** [bas-t/dvbloopback#5]
Hello!

I started dvblast in the configuration file is a SID(among others) for which it does not ffdecsawrapper authorization.
Programs for which authorization has ffdecsawrapper are decoded (visible in oscam_web), but can not be played(vlc).
Subject to dvblast.conf such a SID is not, everything ok.
???

**Comment by bas-t** [comment]
I don't know anything about dvblast, you should seek help in a dvblast forum.
