### ISSUE TITLE
TBS 6905 - saa716x Driver Problem

### ISSUE THREAD

**Issue by sakh251** [bas-t/dvbloopback#6]
System Configuration:
Linux Destru: Mint
Kernel Version: 3.16
DVB-S Cards: 1 quad dvb-s 6905

Configure Command: ./configure --vanilla=3.16 --adapters=36

After Kernel download and compile system boot normally. But the system can not detect our dvb-s cards.  However we can use modprobe dvbloopback adapter= 18 and it create 18 adapters. when  we try install our driver again on  this new kernel we got "disagree about version of symbol" message in dmesg.

Please help us to overcome thin problem and install the cards drivers.

**Comment by bas-t** [comment]
TBS 6905 is not supported by my version of the saa716x driver. It only supports the cards I use, beeing TBS 6281 and TBS 6285
Afaik no opensource driver exists for your card, so you best option whould be using my tbs repo. It compiles the official TBS drivers, with dvbloopback.

So you should do (make sure you've got the headers of your running kernel correctly installed):

git clone https://github.com/bas-t/tbs-dvbloopback.git && cd tbs-dvbloopback

./configure --dvbc=no

This should solve loading the driver, and I sure can't help you should it fail...

**Comment by bas-t** [comment]
BTW: I suggest that you use the default kernel + headers that come with your distro.
Best of luck!

**Comment by sakh251** [comment]
Thanks a lot. It works like charm.

**Comment by bas-t** [comment]
You're welcome!
