### ISSUE TITLE
Si2168 - Appears now as DVB-C and not DVB-T2

### ISSUE THREAD

**Issue by jamesarbrown** [bas-t/dvbloopback#7]
This messes up my terrestrial cards DVBSky T9580 and the card is recognised by the kernel as a DVB-C.... have reinstalled stock kernel and it works. I am guessing it is something to do with the full kernel recompile + non standard si2168 files in the dvbloopback folder?

Was looking for some guide on ffdecsawrapper (which works fine through 14.04LTS) to migrate to dvbloopback + descrambler as just upped to 16.04LTS with 4.4 kernel. lursen.org is down.

Currently trying the ffdescawrapper latest git clone to see if that works.

**Comment by bas-t** [comment]
Have a look at ./configure --help
You may want to run ./configure --drivers=no
or ./configure --dvb=no

**Comment by bas-t** [comment]
BTW, should the output of "./configure --help" be ambiguous to you, please help me to improve it.
English is not my native language,

**Comment by jamesarbrown** [comment]
I had not realised there was a help on the script.... i was looking at the README etc. I will take a look at this.
