### ISSUE TITLE
Ubuntu 16.04 + Genpix Skywalker

### ISSUE THREAD

**Issue by terry-rigby** [bas-t/dvbloopback#8]
Hello there,  I have been following and using your ffdecsawrapper/dvbloopback for a few years now and I just wanted to first say thank you for your work.   I appologize for posting here but I don't know where else to do it.  I used to follow your website (lursen.org I believe it was) for info on the latest use of ffdecsawrapper/dvbloopback and mythtv on Ubuntu.  I'm stuck on Ubuntu 12.04 and I need to upgrade due to some unrelated issues.  I have tried getting descrambler + dvbloopback working in 16.04 but I think I am running into a locking issue with my Genpix Skywalker tuners.  I keep getting the error in dmesg/syslog

```
[  937.926955] gp8psk: usb in 135 operation failed.
[  939.926907] gp8psk: usb out operation failed.
```

  I know this isn't directly related to the git repo for dvbloopback but with your lursen.org site down and dvb.happysat.org gone for good I'm not sure where else to turn.  I have also added the FE_CAN_2G_MODULATION for the genpix driver as well to no avail.

I hope you'd be able to lend me a hand.

**Comment by bas-t** [comment]
I can only try to help you if you've got the source code of the driver you need. And it must be GOOD code, not the crappy shit that people complain about all over the net.
And of course, you need a good firmware for your device.

**Comment by bas-t** [comment]
Probably a better idea: buy a dvb device that is in fact well supported by the linux kernel (v4.4.x and up)

**Comment by bas-t** [comment]
The driver was written by Alan Nisota (alannisota at gmail.com) That's what it says in the source.
I guess he is the one that can help you.
Try to contact him on the v4l mailing list with a CC, you may want to subscribe first.
Linux Media Mailing List linux-media@vger.kernel.org

**Comment by bas-t** [comment]
Hi, I was snooping around and found some modified drivers that are supposed to work with Genpix Skywalker-1, up to linux-4.6.x. Is this what you are looking for?
If those drivers are indeed good, it's quite simple for me to fix your problem.
The author is Chris Lee, a.k.a 'updatelee'
Found his repo here: https://bitbucket.org/updatelee/v4l-updatelee

**Comment by bas-t** [comment]
Ok, I added the mods to a new branch: 'genpix'
So on Ubuntu 16.04 LTS, you can now run

git clone -b genpix https://github.com/bas-t/dvbloopback.git && cd dvbloopback
./configure --genpix=yes

to recompile your stock kernel with the dvbloopback module and the heavily modded genpix driver intree. (and keep your fingers crossed...)
If you need the headers for your new kernel installed, run ./configure --genpix=yes --headers=yes

**Comment by terry-rigby** [comment]
Wow, thank you for your help!

I did manage to get past the kernel lock ups very last night and I am able to tune in mythtv now as well.   I must have made a mistake when configuring the dvbloopback or patching the genpix module.   The only issue I am having is that nothing seems to be passed through to the card server.  I may have something configured incorrectly somewhere along the way.  I'm going to try again using your latest settings and see where that gets me.  Thanks again for your help, I can't say how great it is that you even bothered to respond let alone spend some time to help.

**Comment by bas-t** [comment]
Well, if these patched drivers work for you, you'll probably be in the clear for many years to come. If not, well, it was worth a shot.
The cardserver is another item, maybe I'll get the wiki back online. It's old and I'm not going to update/maintain it, but I guess the basics are all there. Have to think about it though...

**Comment by bas-t** [comment]
Hi, the wiki is online now, but moved from lursen.org to lursen.net

You'll probably want to visit this page:
http://lursen.net/wiki/FFdecsawrapper_with_MythTV_and_Oscam_on_Debian/Ubuntu

or the index: http://lursen.net/wiki/Speciaal:AllePaginas

**Comment by bas-t** [comment]
Compile testing against linux 4.4.x fails. There have been quite a few changes in the dvb subsystem in 4.5.x and up. Going to test against 4.7.7 and 4.8.1
Anyway, you managed to get past the lock ups. Mind posting a how-to for other people?
If it's a big one, please use pastebin and post a link to it here.

**Comment by terry-rigby** [comment]
I did notice that compiling against 4.4.0 fails when using --genpix, I hadn't yet tried to figure out why as I am troubleshooting other unrelated mythtv issues.  I must have made a mistake the first time when running the configure script for the loopback device or maybe somehow I managed to not get the dvb kernel module patched.  I'm going to start fresh again tomorrow and re-run everything to see where I may have gone wrong.  If I figure it out I'll post here.  As of right now all is well though without needing to use updatelee's v4l tree.

**Comment by bas-t** [comment]
OK, I got it. Chris Lee has also heavily modded the dvb core. Just out of curiosity I'll look into this one of these days. Until I do, the genpix branch is defunctional.

**Comment by bas-t** [comment]
There are way too much mods in that dvb core, I don't want to spend that much time on it.
If you are planning on diving into this I suggest you fork this repo and work on it in your fork. I'll delete the genpix branch. Please let me know what you are planning before I do, ok?

**Comment by terry-rigby** [comment]
I've been way too busy to test from a fresh install again.  We just got a new puppy and she is taking over our lives!  That said, I do not believe you need to go down the road of Chris Lee's dvb core.  I was able to get the Genpix module working.  All that is needed is the following patch for the file gp8psk-fe.c   If you can include that in your script it would be pretty cool but if not, I can (I have already) patch and compile on my own.  

```
--- drivers/media/usb/dvb-usb/gp8psk-fe.c.orig  2016-10-17 09:53:43.508471672 -0700
+++ drivers/media/usb/dvb-usb/gp8psk-fe.c   2016-10-17 09:53:50.088719179 -0700
@@ -338,7 +338,7 @@
        .symbol_rate_min        = 1000000,
        .symbol_rate_max        = 45000000,
        .symbol_rate_tolerance  = 500,  /* ppm */
-       .caps = FE_CAN_INVERSION_AUTO |
+       .caps = FE_CAN_2G_MODULATION | FE_CAN_INVERSION_AUTO |
            FE_CAN_FEC_1_2 | FE_CAN_FEC_2_3 | FE_CAN_FEC_3_4 |
            FE_CAN_FEC_5_6 | FE_CAN_FEC_7_8 | FE_CAN_FEC_AUTO |
            /*
```

**Comment by bas-t** [comment]
That would be a single sed line in the patch section of the script, plus a new config option. I can do that.
Have a nice time with your puppy!
